set serveroutput on;

 CREATE TABLE AuditLog (
     LogID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TransactionID NUMBER,
    ActionDate DATE,
    ActionType VARCHAR2(50),
    Description VARCHAR2(255)
 );

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog (TransactionID, ActionDate, ActionType, Description)
    VALUES (:NEW.TransactionID, SYSDATE, 'INSERT', 'Transaction added with amount ' || :NEW.Amount);
END;
/
